Feature/BS-8: list posts index
asilvabe/blog-system pull request #12
Opened 2022-08-18 01:59 UTC by jquevedo82

2022-08-18 13:17 UTC, asilvabe requested changes

2022-08-18 13:17 UTC, asilvabe commented on resources/views/welcome.blade.php
> +                          </table>
No debemos tener código repetido. Esta vista es similar a la vista `posts.index`.

De hecho, esta vista `welcome` debe ser eliminada del proyecto ya que no será más utilizada por la ruta principal.

2022-08-18 13:17 UTC, asilvabe commented on routes/web.php
> +Route::get('/posts', [PostController::class,'index'])->name('posts.index');
Estamos definiendo dos rutas que hacen la misma acción y tienen el mismo nombre.

En este caso la ruta `/posts` podemos decir que está sobrando, y dejar únicamente la ruta `/`.

Para nuestro proyecto, y hasta tanto no se decida lo contrario, la ruta principal será el listado de posts.

2022-08-18 13:17 UTC, asilvabe commented on routes/web.php
> +
Eliminar líneas vacías. Dejar solamente una línea entre el último `use` y la primera ruta.

2022-08-18 13:17 UTC, asilvabe commented on resources/views/posts/index.blade.php
> +                <a href="{{ route('posts.create') }}">Create New Post</a>
Este enlace debe mostrarse únicamente si el usuario está logueado

Puedes apoyarte en la directiva `@auth` para esto

https://laravel.com/docs/8.x/blade#authentication-directives

2022-08-18 13:17 UTC, asilvabe commented on database/seeders/PostSeeder.php
> +        //DB::table('posts')->insert($datos);
Eliminar este código comentado

2022-08-18 13:17 UTC, asilvabe commented on database/seeders/PostSeeder.php
> +      \App\Models\Post::factory(50)->create();
Corregir el identado de esta línea

2022-08-18 13:17 UTC, asilvabe commented on database/seeders/PostSeeder.php
> +    public function run()
Reemplaza el comentario por tipo de retorno en el método

```php
public function run(): void
```

2022-08-18 13:17 UTC, asilvabe commented on database/factories/PostFactory.php
> +        ];
Eliminar líneas sobrantes

2022-08-18 13:17 UTC, asilvabe commented on database/factories/PostFactory.php
> +    public function definition()
Reemplazar comentarios por tipo de retorno, en este caso el método retorna un `array`

2022-08-18 13:17 UTC, asilvabe commented on app/Http/Controllers/PostController.php
> +    public function index()
Agregar tipo de retorno al método, en este caso sería `View`

2022-08-18 14:09 UTC, jquevedo82 commented on routes/web.php
> +Route::get('/posts', [PostController::class,'index'])->name('posts.index');
listo

2022-08-18 14:09 UTC, jquevedo82 commented on routes/web.php
> +
listo

2022-08-18 14:11 UTC, jquevedo82 commented on resources/views/posts/index.blade.php
> +                <a href="{{ route('posts.create') }}">Create New Post</a>
a ok, lo coloque para q sepa el usurio que puede crear posts obvio cuando presiona lo manda a logear.. ya verifico eso, y lo quito de la vista si no esta logeado

2022-08-18 14:12 UTC, jquevedo82 commented on resources/views/welcome.blade.php
> +                          </table>
listoo.....

2022-08-18 14:16 UTC, jquevedo82 commented on database/seeders/PostSeeder.php
> +        //DB::table('posts')->insert($datos);
mala practica, siempre dejo codigo q modifico para recoirdar q tambien lo puedo hacer de otro modo.. ya lo elimine

2022-08-18 14:18 UTC, jquevedo82 commented on database/seeders/PostSeeder.php
> +    public function run()
listo

2022-08-18 14:18 UTC, jquevedo82 commented on database/factories/PostFactory.php
> +        ];
listo

2022-08-18 14:19 UTC, jquevedo82 commented on database/factories/PostFactory.php
> +    public function definition()
listo

2022-08-18 14:20 UTC, jquevedo82 commented on app/Http/Controllers/PostController.php
> +    public function index()
listo

2022-08-18 14:40 UTC, asilvabe requested changes

2022-08-18 14:40 UTC, asilvabe commented on app/Http/Controllers/PostController.php
> -
Cheo estas líneas sí deben dejarse. Revisa este enlace que tiene una explicación de los motivos
https://spatie.be/guidelines/laravel-php#content-whitespace

También por el estándar PSR-12, en él definen que las líneas antes y al final de bloques mayores de código: definición de clases o métodos, finalización de clase, entre otras, son los lugares en donde no deberían dejarse líneas vacías.

> 2.3 Lines
There MUST NOT be a hard limit on line length.

> The soft limit on line length MUST be 120 characters.

> Lines SHOULD NOT be longer than 80 characters; lines longer than that SHOULD be split into multiple subsequent lines of no more than 80 characters each.

> There MUST NOT be trailing whitespace at the end of lines.

> Blank lines MAY be added to improve readability and to indicate related blocks of code except where explicitly forbidden.

> There MUST NOT be more than one statement per line.

https://www.php-fig.org/psr/psr-12/

2022-08-18 15:00 UTC, asilvabe requested changes

2022-08-18 15:00 UTC, asilvabe commented on resources/views/posts/index.blade.php
> +                            </thead>
Cheo tambipen en este bloque ajustar el identado para que sea de 4 espacios como el resto del archivo

2022-08-19 18:53 UTC, asilvabe approved these changes

2022-08-19 18:53 UTC, merged