Feature/BS-4: Aapproved user in show
asilvabe/blog-system pull request #18
Opened 2022-08-22 20:56 UTC by jquevedo82

2022-08-23 00:58 UTC, asilvabe requested changes

2022-08-23 00:58 UTC, asilvabe commented on app/Models/Post.php
> +    public function approving(): BelongsTo
El nombre de este método se traduce a algo así como "aprobando". Sería mejor usar "approver" para referirnos a la persona quien aprueba.

2022-08-23 00:58 UTC, asilvabe commented on database/factories/PostFactory.php
> +            'approved_by' => null,
En el factory no es necesario definir que estos campos se inicializan con `null` porque desde la definición de la tabla se crean con `null` por defecto.

2022-08-23 00:58 UTC, asilvabe commented on database/seeders/DatabaseSeeder.php
> +}
Por convención de GIT, siempre debemos dejar una línea vacía al final de todos los archivos.

2022-08-23 00:58 UTC, asilvabe commented on resources/views/posts/show.blade.php
> +                        <p>Approved by:{{ isset($post->approving) ? $post->approving->name : 'Pendiente' }}</p>
No debemos tener lógica de negocio en las vistas. Por ahora, una forma temporal de mejorarlo es mover esta lógica al modelo, puede ser un método que podemos llamar `getApproverName()`, que retorne el nombre del aprobador o en su defecto la palabra "Pendiente".

Luego veremos una forma más robusta de hacerlo usando un patrón llamado "View models"

2022-08-23 01:00 UTC, asilvabe commented
@jquevedo82 moví la tarea en Jira a "Pendiente". Recuerda moverlo nuevaente a "en curso" y luego a "para revisar" cuando subas las modificaiones

2022-08-23 11:14 UTC, jquevedo82 commented on database/factories/PostFactory.php
> +            'approved_by' => null,
ok los voy a quitar y volver a aprobar, porq me parecio que daba error, cuando no los definia. por eso los coloque, pero ya verifico...

2022-08-23 11:15 UTC, jquevedo82 commented on database/seeders/DatabaseSeeder.php
> +}
ok. lo tomare en cuenta de ahora en adelante

2022-08-23 11:16 UTC, jquevedo82 commented on resources/views/posts/show.blade.php
> +                        <p>Approved by:{{ isset($post->approving) ? $post->approving->name : 'Pendiente' }}</p>
ok... lo movere al modelo.. y creo la funcion

2022-08-23 12:32 UTC, asilvabe requested changes

2022-08-23 12:32 UTC, asilvabe commented on app/Models/Post.php
> +    }
Este método está sobrando ya que no hace ninguna acción o transformación sobre `approved_at`.

En este caso, no importa si llamamos a `approved_at` directamente en la vista, porque es una propiedad pública dle modelo.

En el caso del nombre del aprobador hay una cierta lógica que es el caso que no debemos ponerlo en las vistas, ya que es probable que se utiice en varias partes del sistema

2022-08-23 12:32 UTC, asilvabe commented on resources/views/posts/show.blade.php
> +                        <p>Date:{{ $post->getApproverDate() }}</p>
Dejar como estaba `$post->approved_at`

2022-08-24 00:16 UTC, asilvabe requested changes

2022-08-24 00:16 UTC, asilvabe commented on resources/views/posts/show.blade.php
> +                        <p>Date: {{ $post->approved_at }}</p>
La etiqueta `Date` debe ser más descriptiva
¿Es la fecha de qué cosa?

2022-08-24 00:16 UTC, asilvabe commented on resources/views/posts/show.blade.php
> +                        @if(is_null($post->approved_at))
Aquí queda mejor agregar un método al modelo para preguntarle si está aprobado. Similar al `isAdmin()` de User

2022-08-24 00:16 UTC, asilvabe commented on app/Models/Post.php
> +
Eliminar línea en blanco sobrante

2022-08-24 00:16 UTC, asilvabe commented on app/Http/Controllers/ApprovePostController.php
> +    public function __invoke(Post $post): view
Cambiar tipo de retorno `view` por `View`

2022-08-24 00:16 UTC, asilvabe commented on app/Http/Controllers/ApprovePostController.php
> +        $post->approved_by=auth()->user()->id;
Dejar un espacio antes y después del operador de asignación `=`

```php
$post->approved_at = now();
$post->approved_by = auth()->user()->id;
```

El objeto Carbon no se justifica en este método, reemplazarlo por ela función `now()` de PHP

2022-08-24 00:16 UTC, asilvabe commented on resources/views/posts/show.blade.php
>                  <a href ="{{ route('posts.index') }}">Regresar</a>
Por razones de seguridad, es conveniente usar un formulario para esta acción, ya que es una acción protegida para usuarios autenticados y administradores.

Revisa esta parte de la documentación de Laravel, que ofrece un mecanismo de seguridad para llamar rutas post, patch, update, delete, evitando una vulnerabilidad conocida como [Cross-site request forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery)

https://laravel.com/docs/9.x/csrf#main-content

Luego de haber comprendido las implicaciones, una mejor forma sería:

```php
<form method="POST" action="{{ route('posts.approver', $post) }}">
    @csrf
    @method('PATCH')
    <button type="submit">Approve post</button>
</form><a href="{{ route('posts.approve', $post) }}">Approve</a>
```

La ruta posts.approve debería ser definida con el verbo PATCH

No nos preocupemos mucho por ahora de la parte visual

2022-08-24 00:16 UTC, asilvabe commented on resources/views/posts/show.blade.php
> +                    @if ( auth()->user()->isAdmin())
Eliminar espacio después del parpentesis de apertura

2022-08-24 00:16 UTC, asilvabe commented on routes/web.php
> +    Route::get('posts/{post}/approve', ApprovePostController::class)->name('posts.approver');
La ruta no debe ser de tipo `get` ya que no estamos pidiendo un recurso sino que lo estamos modificando.

En este caso debe ser PATCH porque estamos modificando parcialmente una publcación.

https://developer.mozilla.org/es/docs/Web/HTTP/Methods

El nombre de la ruta queda mejor `posts.approve`

```php
Route::patch('posts/{post}/approve', ApprovePostController::class)->name('posts.approve');
```

2022-08-24 12:21 UTC, jquevedo82 commented on routes/web.php
> +    Route::get('posts/{post}/approve', ApprovePostController::class)->name('posts.approver');
si alex, hoy antes de ver tus comentarios en el bondi venia pensando en q no era tipo get, pense q era post pero te iba a preguntar, y abrir el correo y vi lo q habias comentado...

2022-08-24 12:22 UTC, jquevedo82 commented on app/Http/Controllers/ApprovePostController.php
> +        $post->approved_by=auth()->user()->id;
busque fue cual utilizaba laravel pero cierto q es php

2022-08-24 22:45 UTC, asilvabe requested changes

2022-08-24 22:45 UTC, asilvabe commented on app/Http/Controllers/ApprovePostController.php
> +        $post->approved_by=auth()->user()->id;
Está pendiente aún los espacios en los operadores `=`

2022-08-24 22:45 UTC, asilvabe commented on app/Models/Post.php
> +    public function is_approve(): string
Por convención, los nombres de los métodos deben ser creados con `lowerCamelCase`

Para este método sería `isApprove()`

La convención `snake_case` suele usarse para nombres de campos de tablas y para keys en arreglos

2022-08-25 01:05 UTC, jquevedo82 commented on app/Models/Post.php
> +    public function is_approve(): string
listo. entendido, justo hoy vi eso en una cosa q estaba montando en nestjs.. nest crea la estructura de la base de datos, entonces q se puede establecer un nombre para la tabla y sus atributos y otro para el nombre del atributo en el modelo de la clase..

2022-08-25 01:06 UTC, jquevedo82 commented on app/Models/Post.php
> +
listo

2022-08-25 01:08 UTC, jquevedo82 commented on app/Http/Controllers/ApprovePostController.php
> +        $post->approved_by=auth()->user()->id;
ok.. lei el comentario de la parte de abajo y no el de arriba

2022-08-25 12:04 UTC, asilvabe approved these changes

2022-08-25 23:37 UTC, merged