Feature/BS-15: setting page.
asilvabe/blog-system pull request #19
Opened 2022-08-23 13:06 UTC by biskukuy

cree una tabla que guardara el objetivo y propósito de nuestro blog.

2022-08-24 00:30 UTC, asilvabe requested changes
Hace falta una funcionalidad que permita únicamente a los usuarios administradores editar o registrar por primera vez estos datos del blog.

2022-08-24 00:30 UTC, asilvabe commented on database/seeders/DatabaseSeeder.php
> +        ]);
Para poder usar un Factory es necesario crear la respectiva clase en la carpeta `database/factories`. En este caso una clase que debe llamarse `SettingFactory`

En este momento genera error al correr el seeder por la falta del factory.

![image](https://user-images.githubusercontent.com/2821564/186288132-869f0d2c-2e16-479d-bd74-1a13139315cf.png)

2022-08-24 00:30 UTC, asilvabe commented on database/seeders/DatabaseSeeder.php
> +
Eliminar líneas en blanco sobrantes

2022-08-24 00:30 UTC, asilvabe commented on database/seeders/DatabaseSeeder.php
> +            'purpose' => config(key: 'Proposito del Blog'),
El helper `config()` está siendo mal utilizado. Esta instrucción dará error luego de haber creado el Factory para Setting

Recuérdame el viernes explicarles cómo funciona `config()` y en qué casos debe utilizarse

2022-08-24 00:30 UTC, asilvabe commented on app/Http/Controllers/SettingController.php
> +    public function index(): View
El método `index` usualmente se usa para entregar un listado de recursos al usuario.

Para este caso es más adecuado tal vez usar edit o show.

2022-08-24 00:30 UTC, asilvabe commented on database/migrations/2022_08_22_212140_create_settings_table.php
> +            $table->string('purpose',200);
¿cuál sería la diferencia entre objetivo y propósito?

2022-08-24 00:30 UTC, asilvabe commented on database/migrations/2022_08_22_212140_create_settings_table.php
> +    public function down()
Agregar tipo de retorno al método, `void`

2022-08-24 00:30 UTC, asilvabe commented on resources/views/about/index.blade.php
> +</html>
Esta vista en realidad está mostrando un registro de la BD, sebería ser `show` en vez de `index`

Por otro lado, cuando no existe un registro en la base de datos, la aplicación se rompe al intentar mostrar un setting que no logra traer de la BD

![image](https://user-images.githubusercontent.com/2821564/186288795-d353ab6b-83c6-4ce4-9ea4-0b0a6b08031f.png)

2022-08-25 11:22 UTC, biskukuy commented on database/seeders/DatabaseSeeder.php
> +        ]);
reparado

2022-08-25 11:22 UTC, biskukuy commented on database/seeders/DatabaseSeeder.php
> +
reparado

2022-08-25 11:22 UTC, biskukuy commented on database/seeders/DatabaseSeeder.php
> +            'purpose' => config(key: 'Proposito del Blog'),
corregido

2022-08-25 11:23 UTC, biskukuy commented on database/migrations/2022_08_22_212140_create_settings_table.php
> +            $table->string('purpose',200);
me iamgino que es como el objetivo sera algo como el slogan y el proposito será mas a detalle...

2022-08-25 11:23 UTC, biskukuy commented on resources/views/about/index.blade.php
> +</html>
listo, fue corregido.

2022-08-25 23:45 UTC, asilvabe requested changes

2022-08-25 23:45 UTC, asilvabe commented on database/factories/SettingFactory.php
> +            'purpose'=> "La idea es crear un proyecto que sea capaz de competir con las redes de mercado",
En los factories la idea es generar datos aleatorios, tanto para a nivel de pruebas manuales como para las automatizadas.

En este caso puedes usar el método `sentence()` para los objetivos del blog y `paragraph()` para el propósito.

```php
 'objective'=> $this->faker->sentence(),
 'purpose'=> $this->faker->paragraph(),
 ```

2022-08-25 23:45 UTC, asilvabe commented on database/seeders/DatabaseSeeder.php
> +
Siguen estando presentes las líneas en blanco (líneas 30 y 31 del archivo)

2022-08-25 23:45 UTC, asilvabe commented on database/seeders/DatabaseSeeder.php
> +        ]);    }
La llave de cierre debe ir en la línea siguiente

2022-08-25 23:52 UTC, asilvabe commented on resources/views/about/index.blade.php
> +</html>
Sigue generando error cuando la tabla settings está vacía.

Esto es porque en la vista se intenta acceder a las propiedades `objetive` y `purpose` estando el objeto `$setting` vacío cuando no hay datos.

¿cómo lo solucionarías?

2022-08-25 23:53 UTC, asilvabe commented on database/migrations/2022_08_22_212140_create_settings_table.php
> +    public function down()
Esto sigue pendiente

2022-08-25 23:53 UTC, asilvabe commented on app/Http/Controllers/SettingController.php
> +    public function index(): View
Esto sigue pendiente

2022-09-13 23:36 UTC, asilvabe commented
Se cambió el enfoque del módulo

2022-09-13 23:36 UTC, closed without merging