Feact 2
asilvabe/blog-system pull request #2
Opened 2022-08-06 16:44 UTC by biskukuy

le agregue al proyecto: el controlador de las publicaciones, la vista para crear las publicaciones, y los estilos de bootstrap

2022-08-08 14:28 UTC, asilvabe requested changes

2022-08-08 14:28 UTC, asilvabe commented on app/Http/Controllers/PostController.php
> +    }
Eliminar todos los métodos del controlador que no se estén utiizando.

A medida de que vayamos agregando funcionalidades, se irán creando los métodos se que se necesiten.

2022-08-08 14:28 UTC, asilvabe commented on app/Http/Controllers/PostController.php
> +    public function create()
Como equipo, vamos a usar un estándar que consiste en reemplazar los comentarios docblocks de PHP  por tipos de retorno en los métodos.

En este método consiste en eliminar el comentario y agregar el tipo `View`, así:

```php
public function create(): View
{
    ....
```

Es muy importante fijarse en los espacios. Los dos puntos deben ir inmediatamente después del paréntesis de cierre, luego un espacio y luego el tipo. En este caso `View`

La ruta completa de la clase `View` debe agregarse como un import al inicio del archivo.

`use Illuminate\View\View;`

2022-08-08 14:28 UTC, asilvabe commented on app/Http/Controllers/PostController.php
> +    public function store(Request $request)
Cambiar comentario por tipo de retorno.

En este caso el tipo es `\Illuminate\Http\Response`, que es el tipo que devuelve el helper `to_route()`

2022-08-08 14:28 UTC, asilvabe commented on app/Http/Controllers/PostController.php
> +
Eliminar línea vacía

2022-08-08 14:28 UTC, asilvabe commented on app/Http/Controllers/PostController.php
> +        $post->created_date = $request->input('created_date');
Eliminar esta instrucción.

La fecha de creación del registro la guarda Laravel automáticamente.

Esta columna debió eliminarse de la migración de los posts.

2022-08-08 14:28 UTC, asilvabe commented on database/migrations/2022_08_07_172256_create_posts_table.php
> +            $table->timestamp('created_date');
Este campo está sobrando.

El método `timestamps()` crea automáticamente dos campos `created_at` y `updated_at`. Y Laravel los actualiza automáticamente según el caso.

2022-08-08 14:28 UTC, asilvabe commented on database/migrations/2022_08_07_172256_create_posts_table.php
> +    public function up()
Reemplazar comentarios por tipo de retorno.

Hacerlo para el método `down()` también.

Aplicar este enfoque para toda la aplicación de ahora en adelante. Solamente en los archivos que se modifiquen en cada tarea que se trabaje.

2022-08-08 14:28 UTC, asilvabe commented on resources/views/posts/create.blade.php
> +                <input type="text" class="form-control" id="title" name="title" placeholder="Write text here" value="{{old('title')}}">
De manera consistente, dejar siempre un espacio en blanco luego de cada `{{` y antes de cada `}}`.

2022-08-08 14:28 UTC, asilvabe commented on resources/views/posts/create.blade.php
> +            </div>
Eliminar. No debemos solicitar la fecha de creación al usuario.

2022-08-08 14:28 UTC, asilvabe commented on routes/web.php
> +Route::post('/posts', [PostController::class,'store'] )->name('posts.store');
Eliminar el `/` en la URI de la ruta. Es por tema de convención del equipo.

2022-08-08 14:28 UTC, asilvabe commented on app/Http/Controllers/PostController.php
> +            'created_date' => ['required']
Eliminar la regla de validación para el dato `created_date`

2022-08-10 11:07 UTC, biskukuy commented on app/Http/Controllers/PostController.php
> +    }
ok, listo, me pondré a realizarlo

2022-08-10 11:14 UTC, biskukuy commented on app/Http/Controllers/PostController.php
> +    public function create()
ok, información agregada correctamente

2022-08-10 11:18 UTC, biskukuy commented on app/Http/Controllers/PostController.php
> +    public function store(Request $request)
hice el cambio por el que me indicaste y me dio error, pero extrapolando el error que me mostró el navegador le coloque _use Illuminate\Http\RedirectResponse;_  
`  public function store(Request $request): RedirectResponse`
y funcionó, ¿es correcta mi solución?

2022-08-11 13:27 UTC, asilvabe approved these changes

2022-08-11 13:28 UTC, merged