BS-4_register_user
asilvabe/blog-system pull request #3
Opened 2022-08-07 22:13 UTC by jquevedo82

create a user in the database

2022-08-07 23:30 UTC, asilvabe requested changes

2022-08-07 23:30 UTC, asilvabe commented on database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
> +    public function up()
Como equipo, vamos a usar un estándar que consiste en reemplazar los comentarios docblocks de PHP  por tipos de retorno en los métodos.

En este método consiste en eliminar el comentario y agregar el tipo `void`, así:

```php
public function up(): void
{
    ....
```

Es muy importante fijarse en los espacios. Los dos puntos deben ir inmediatamente después del paréntesis de cierre, luego un espacio y luego el tipo. En este caso `void`

Ajustar en los otros métodos de esta clase.

2022-08-07 23:30 UTC, asilvabe commented on database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
> +<?php
No se si esta migración la creó fortify automáticamente.

Pero si no es asi, es mejor elminarla, porque el ticket no contempla la implementación de 2FA en el sistema

2022-08-07 23:30 UTC, asilvabe commented on database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
> +
Corregir este identado.

Cuando utilices saltos de línea para métodos encadenados, los métodos en la nueva línea deben tener sólo un nivel de identado.

```php
$table->text('two_factor_secret')
    ->after('password')
    ->nullable();
```

2022-08-07 23:30 UTC, asilvabe commented on resources/views/auth/register.blade.php
> +                                value="{{ old('name') }}">
En ciertas ocasiones no es necesario o conveniente agregar saltos de línea, aunque se excedan los 80 caracteres.

Eliminar este salto.

2022-08-07 23:30 UTC, asilvabe commented on resources/views/auth/register.blade.php
> +                                value="{{ old('email') }}">
Eliminar salto de línea

2022-08-07 23:30 UTC, asilvabe commented on resources/views/auth/register.blade.php
> +                                placeholder="Confirm Password">
Eliminar salto de línea

2022-08-07 23:30 UTC, asilvabe commented on resources/views/auth/register.blade.php
> +<!DOCTYPE html>
Es necesario mostrar al usuario cuando existen errores de validación.

Para esta iteración, basta con agregar el código que está en la documentación:
https://laravel.com/docs/9.x/validation#quick-displaying-the-validation-errors

2022-08-07 23:30 UTC, asilvabe commented on resources/views/welcome.blade.php
> +
Eliminar este salto de línea

2022-08-07 23:30 UTC, asilvabe commented on resources/views/home.blade.php
> +{{auth()->user();}}
Cuando inyectamos PHP en plantillas Blade con `{{ }}` no es necesario utilizar el punto y coma.

También es buena práctica dejar un espacio entre las llaves y el contenido:

`{{ auth()->user() }}`

2022-08-07 23:59 UTC, jquevedo82 commented on database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
> +<?php
La migracion fue creada por el fortify, yo no cree ninguna migracion..

2022-08-07 23:59 UTC, jquevedo82 commented on database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
> +    public function up()
ok.. ya las revise y modifique.

2022-08-08 00:00 UTC, jquevedo82 commented on database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
> +
tengo que tener cuidado porque el formateador que tengo instalado en vsc lo hace por defecto. ya lo estoy corrigiendo.

2022-08-08 00:01 UTC, jquevedo82 commented on resources/views/auth/register.blade.php
> +                                value="{{ old('name') }}">
ok. listo. tendre presente lo del formateador de vsc

2022-08-08 00:01 UTC, jquevedo82 commented on resources/views/auth/register.blade.php
> +                                value="{{ old('email') }}">
listo.

2022-08-08 00:01 UTC, jquevedo82 commented on resources/views/auth/register.blade.php
> +                                placeholder="Confirm Password">
listo.

2022-08-08 14:47 UTC, asilvabe commented on database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
> +<?php
@jquevedo82 por favor elimina esta migración del la rama, y sube el cambio al PR

2022-08-08 15:33 UTC, closed without merging