Feature/bs-4: user registration
asilvabe/blog-system pull request #5
Opened 2022-08-08 15:37 UTC by jquevedo82

2022-08-08 17:36 UTC, asilvabe requested changes
@jquevedo82 en este caso, todos los cambios solicitados en esta revisión, pueden hacerse en un mismo commit, porque todo está relacionado con una misma cosa: estido de código.

No siempre será de esta manera.

Recuerda hacer el commit, luego el push, y GitHub automáticamente actualiza el PR.

2022-08-08 17:36 UTC, asilvabe commented on database/migrations/2014_10_12_000000_create_users_table.php
> +
Eliminar línea vacía

No debe existir una linea en blanco entre la llave de apertura de la clase y la primera declaración de la clase.

https://www.php-fig.org/psr/psr-12/

2022-08-08 17:36 UTC, asilvabe commented on database/migrations/2014_10_12_000000_create_users_table.php
> +
Eliminar línea sobrante

2022-08-08 17:36 UTC, asilvabe commented on database/migrations/2014_10_12_100000_create_password_resets_table.php
> +
Eliminar línea vacía

2022-08-08 17:36 UTC, asilvabe commented on database/migrations/2014_10_12_100000_create_password_resets_table.php
> +
Eliminar línea vacía

2022-08-08 17:36 UTC, asilvabe commented on database/migrations/2019_08_19_000000_create_failed_jobs_table.php
> +
Eliminar línea vacía

2022-08-08 17:36 UTC, asilvabe commented on database/migrations/2019_08_19_000000_create_failed_jobs_table.php
> +
Eliminar línea vacía

2022-08-08 17:36 UTC, asilvabe commented on routes/web.php
> +Route::view('home','home');
Para aprovechar que estarás haciendo modificaciones de estilo de código, agrega un espacio en blanco después de la coma:

`Route::view('home', 'home');`

https://www.php-fig.org/psr/psr-12/

2022-08-09 00:44 UTC, jquevedo82 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +
en el codigo ya estaba corregido.

2022-08-09 00:44 UTC, jquevedo82 commented on database/migrations/2014_10_12_100000_create_password_resets_table.php
> +
listo.

2022-08-09 00:44 UTC, jquevedo82 commented on database/migrations/2014_10_12_100000_create_password_resets_table.php
> +
listo

2022-08-09 00:44 UTC, jquevedo82 commented on database/migrations/2019_08_19_000000_create_failed_jobs_table.php
> +
ya en el codigo que estaba en el ultimo codigo ya se habia corregido

2022-08-09 00:44 UTC, jquevedo82 commented on routes/web.php
> +Route::view('home','home');
tome en cuenta y realice la modificacion

2022-08-11 12:46 UTC, asilvabe commented on database/migrations/2014_10_12_000000_create_users_table.php
> +
@jquevedo82 probablemente este cambio lo tienes en tu local pero aún no lo has subido al repositorio

2022-08-11 12:46 UTC, asilvabe commented on database/migrations/2014_10_12_100000_create_password_resets_table.php
> +
Estos cambios no están en el repositorio aún

2022-08-11 12:47 UTC, asilvabe commented on database/migrations/2014_10_12_100000_create_password_resets_table.php
> +
Repositorio por actualizar

2022-08-11 14:11 UTC, asilvabe approved these changes

2022-08-11 14:12 UTC, merged